spring:
  profiles:
    active: development
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
logging.level.org.springframework.security: DEBUG
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://192.168.0.114:3306/dev
    username: root
    password: dbpass
    initialize: true
security.ignored: /resources/**
testValue: user value
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.114:9092
          zk-nodes: 192.168.0.114:2182
security.ignored: /resources/**
testValue: config value
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
